[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cf-plot"
version = "3.5.0"
description = "Code-light plotting for earth science and aligned research"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [{ name = "Andy Heaps", email = "andy.heaps@ncas.ac.uk" }]
maintainers = [
    {name = "Sadie Bartholomew", email = "sadie.bartholomew@ncas.ac.uk" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Operating System :: Unix",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
]
requires-python = ">=3.10"
dependencies = [
    "cf-python>=3.17.0",
    "scipy>=1.4.0",
    "cartopy>=0.22.0",
]

[project.urls]
Homepage = "https://ncas-cms.github.io/cf-plot/"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["cfplot*"]

[tool.setuptools.package-data]
cfplot = ["colour/colourmaps/*"]

# To run the black checker with this configuration, execute 'black .' in the
# root of this repository. See https://black.readthedocs.io/en/stable/ for
# the 'black' documentation.
[tool.black]
line-length = 79

[tool.isort]
# Set for compatibility of 'black' and 'isort' auto-formatting tools
profile = "black"
# ... and since we set this against the black default line length:
line_length=79
